### ISSUE TITLE
Make automatic HA restart optional

### ISSUE THREAD

**Issue by tbclark3** [amitfin/patch#68]
### Checklist

- [X] I have filled out the template to the best of my ability.
- [X] This only contains 1 feature request (if you have multiple feature requests, open one feature request for each feature request).
- [X] This issue is not a duplicate feature request of [previous feature requests](https://github.com/amitfin/patch/issues?q=is%3Aissue+label%3A%22Feature+Request%22+).

### Is your feature request related to a problem? Please describe.

It is not always necessary, and not always desirable to restart Home Assistant after a patch is applied. 

### Describe the solution you'd like

Add a configuration parameter such as "Automatic Home Assistant Restart:  True|False"

### Describe alternatives you've considered

I uninstalled this integration when I figured out that there was no way to disable the automatic HA restart.

### Additional context

This would be a very easy addition.

**Comment by amitfin** [comment]
Can you elaborate on the scenario? How do you know that a restart is not required? 
(I'm trying to understand the scenario so I can better document this new option and when it should be used.)

**Comment by amitfin** [comment]
[v1.6.0](https://github.com/amitfin/patch/releases/tag/v1.6.0) adds a new `restart` optional parameter. Default is true. When it's set to false, there is no HA restart after a patch.

I'm still curious to better understand the use case here.

**Comment by tbclark3** [comment]
First, THANK YOU for your very prompt response! I use systemd to manage HA, and if systemd detects that HA has stopped, it will stop it, remove the container, and restart it. As long as systemd is the only thing restarting HA, it works smoothly and keeps good logs. Allowing Patch to restart would lead to a circle of restarts that would never end. In addition, restarting for me is not without issues thanks to several quasi-stable integrations. Iwatch the logs during a restart to see if anything pops up that I need to fix and restart a second time. Finally, although I know this is to some degree a crapshoot, if Patch runs before the patched file is needed, then there is no need for a restart.

**Comment by amitfin** [comment]
Thanks for sharing the details! Sounds fair. 
Closing the issue.
